
export class OllamaProvider {
  constructor(public endpoint: string) {}
  
  async generate(request: any): Promise<any> {
    // Ollama implementation
    return { content: 'Generated by Ollama', model: 'ollama' };
  }
  
  async checkStatus(): Promise<boolean> {
    return true;
  }
}
